services:
  - type: web
    name: backend-server
    env: node
    plan: starter
    buildCommand: npm run build
    startCommand: npm run start
    repo: https://github.com/brandandvisual/pure-fish-server
    branch: main
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /health